import{a as b,S as v,i as d}from"./assets/vendor-DEenWwFD.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function i(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=i(e);fetch(e.href,o)}})();async function f(t,s,i){const a={key:"47659008-74bbb6b2c2d0fee0411ee57da",q:t.trim(),image_type:"photo",orientation:"horizontal",safesearch:!0,page:s,per_page:i};return(await b.get("https://pixabay.com/api/",{params:a})).data}function g(t){return t.map(({webformatURL:s,largeImageURL:i,tags:a,likes:e,views:o,comments:l,downloads:L})=>`<li class="list-item">
  <a href="${i}" alt="${a}" title="">
    <img src="${s}" alt="${a}" class="img-item">
  <div class="list-container">
  <p class="item"><span class="item-text">Likes</span> <span>${e}</span></p>
  <p class="item"><span class="item-text">Wiews</span> <span>${o}</span></p>
  <p class="item"><span class="item-text">Comments</span> <span>${l}</span></p>
  <p class="item"><span class="item-text">Downlods</span> <span>${L}</span></p>
  </div></a>
</li>`).join("")}const y=new v(".gallery a",{captionsData:"alt",captionDelay:250,captionClass:"imageTitle"}),w=document.querySelector(".form"),p=document.querySelector(".gallery"),n=document.querySelector(".loader"),r=document.querySelector(".load-btn");let m=1,h=1;const u=15;let c;w.addEventListener("submit",M);r.addEventListener("click",$);function M(t){if(t.preventDefault(),m=1,c=t.target.elements.search.value.trim(),console.log(c),p.innerHTML="",n.innerHTML="",r.classList.add("hidden"),!c){d.show({message:"Please add request!",position:"center",color:"red"}),p.innerHTML=":(";return}n.classList.remove("hidden"),f(c,m,u).then(s=>{console.log(s);const{hits:i,totalHits:a}=s;h=Math.ceil(a/u),i.length?(console.log(i),p.innerHTML=g(i),y.refresh(),h===1?r.classList.add("hidden"):r.classList.remove("hidden")):(d.show({message:"Sorry, there are no images matching your search query. Please try again!",position:"center",color:"red"}),n.innerHTML="<h1>Error..</h1>",r.classList.add("hidden"))}).catch(s=>{console.log(s.message),d.show({message:`${s.message}`,position:"center",color:"red"})}).finally(()=>{t.target.elements.search.value="",n.classList.add("hidden")})}async function $(){m+=1,r.classList.add("hidden"),n.classList.remove("hidden");try{const{hits:t,totalHits:s}=await f(c,m,u);p.insertAdjacentHTML("beforeend",g(t)),h=Math.ceil(s/u),m>h?(r.classList.add("hidden"),d.show({message:"We're sorry, but you've reached the end of search results.",position:"center",color:"red"})):r.classList.remove("hidden"),setTimeout(()=>{const a=document.querySelector(".list-item").getBoundingClientRect().height;window.scrollBy({left:0,top:a*2,behavior:"smooth"})},0),y.refresh()}catch(t){console.log(t.message),d.show({message:`${t.message}`,position:"center",color:"red"})}finally{r.disabled=!1,n.classList.add("hidden")}}
//# sourceMappingURL=index.js.map
