import{a as b,S as w,i as d}from"./assets/vendor-DEenWwFD.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))a(e);new MutationObserver(e=>{for(const o of e)if(o.type==="childList")for(const l of o.addedNodes)l.tagName==="LINK"&&l.rel==="modulepreload"&&a(l)}).observe(document,{childList:!0,subtree:!0});function r(e){const o={};return e.integrity&&(o.integrity=e.integrity),e.referrerPolicy&&(o.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?o.credentials="include":e.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function a(e){if(e.ep)return;e.ep=!0;const o=r(e);fetch(e.href,o)}})();async function f(s,t,r){const a={key:"47659008-74bbb6b2c2d0fee0411ee57da",q:s.trim(),image_type:"photo",orientation:"horizontal",safesearch:!0,page:t,per_page:r};return(await b.get("https://pixabay.com/api/",{params:a})).data}function g(s){return s.map(({webformatURL:t,largeImageURL:r,tags:a,likes:e,views:o,comments:l,downloads:L})=>`<li class="list-item">
  <a href="${r}" alt="${a}" title="">
    <img src="${t}" alt="${a}" class="img-item">
  <div class="list-container">
  <p class="item"><span class="item-text">Likes</span> <span>${e}</span></p>
  <p class="item"><span class="item-text">Wiews</span> <span>${o}</span></p>
  <p class="item"><span class="item-text">Comments</span> <span>${l}</span></p>
  <p class="item"><span class="item-text">Downlods</span> <span>${L}</span></p>
  </div></a>
</li>`).join("")}const y=new w(".gallery a",{captionsData:"alt",captionDelay:250,captionClass:"imageTitle"}),v=document.querySelector(".form"),p=document.querySelector(".gallery"),n=document.querySelector(".loader"),i=document.querySelector(".load-btn");let m=1,u=1;const h=15;let c;v.addEventListener("submit",M);i.addEventListener("click",$);function M(s){if(s.preventDefault(),c=s.target.elements.search.value.trim(),console.log(c),p.innerHTML="",n.innerHTML="",!c){d.show({message:"Please add request!",position:"center",color:"red"}),p.innerHTML=":(";return}n.classList.remove("hidden"),f(c,m,h).then(t=>{console.log(t);const{hits:r,totalHits:a}=t;u=Math.ceil(a/h),r.length?(console.log(r),p.innerHTML=g(r),y.refresh(),m===u?i.classList.replace("load-btn","hidden"):i.classList.replace("hidden","load-btn")):(d.show({message:"Sorry, there are no images matching your search query. Please try again!",position:"center",color:"red"}),n.innerHTML="<h1>Error..</h1>")}).catch(t=>{console.log(t.message),d.show({message:`${t.message}`,position:"center",color:"red"})}).finally(()=>{s.target.elements.search.value="",n.classList.add("hidden")})}async function $(){m+=1,i.disabled=!0,n.classList.remove("hidden");try{const{hits:s,totalHits:t}=await f(c,m,h);p.insertAdjacentHTML("beforeend",g(s)),u=Math.ceil(t/h),m>u&&(i.classList.replace("load-btn","hidden"),d.show({message:"We're sorry, but you've reached the end of search results.",position:"center",color:"red"})),setTimeout(()=>{const a=document.querySelector(".list-item").getBoundingClientRect().height;window.scrollBy({left:0,top:a*2,behavior:"smooth"})},0),y.refresh()}catch(s){console.log(s.message),d.show({message:`${s.message}`,position:"center",color:"red"})}finally{i.disabled=!1,n.classList.add("hidden")}}
//# sourceMappingURL=index.js.map
